In [75]:
import psycopg2 as pq
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from datetime import datetime
from itertools import chain

In [219]:
with pq.connect('postgresql://localhost:5432/golf') as conn:
    with conn.cursor() as cursor:
        sqlTxt = '''
        select    year, date, player_id, tourn_id, round,  count(shot) as score
          from    strokes 
          where   player_id = '28237'
            and   year = 2016
          group by year, date, player_id, tourn_id, round
          order by date, tourn_id, round
        '''
        cursor.execute(sqlTxt)
        rounds = np.empty((1, 6))
        for row in cursor:
            rounds = np.vstack((rounds, np.asarray(row).reshape((1,6))))
        rounds = rounds[1:,2:]
                  

In [222]:
def combine_rounds(rounds):
    def round_equals(row1, row2): 
        return row1[0] == row2[0] and row1[1] == row2[1] and row1[2] == row2[2]
    last = rounds[0]  
    result = last
    for round in rounds[1:]:
        if round_equals(last, round):
            round[3] += last[3]
        else:
            result = np.vstack((result, round))
        last = round
    return result
                           
combine_rounds(rounds)

array([[28237L, 10L, 1L, 68L],
       [28237L, 10L, 2L, 72L],
       [28237L, 10L, 3L, 71L],
       [28237L, 10L, 4L, 69L],
       [28237L, 160L, 1L, 67L],
       [28237L, 160L, 2L, 69L],
       [28237L, 160L, 3L, 68L],
       [28237L, 160L, 4L, 75L],
       [28237L, 170L, 1L, 72L],
       [28237L, 170L, 2L, 75L],
       [28237L, 180L, 1L, 71L],
       [28237L, 180L, 2L, 65L],
       [28237L, 180L, 3L, 68L],
       [28237L, 180L, 4L, 75L],
       [28237L, 200L, 1L, 78L],
       [28237L, 200L, 2L, 67L],
       [28237L, 200L, 3L, 78L],
       [28237L, 200L, 4L, 65L],
       [28237L, 220L, 1L, 74L],
       [28237L, 220L, 2L, 57L],
       [28237L, 220L, 3L, 68L],
       [28237L, 280L, 1L, 73L],
       [28237L, 280L, 2L, 70L],
       [28237L, 280L, 3L, 74L],
       [28237L, 280L, 4L, 66L],
       [28237L, 290L, 1L, 73L],
       [28237L, 290L, 2L, 64L],
       [28237L, 290L, 3L, 75L],
       [28237L, 290L, 4L, 71L],
       [28237L, 320L, 1L, 71L],
       [28237L, 320L, 2L, 67L],
       [2823

In [201]:
rounds

array([[28237L, 10L, 1L, 68L],
       [28237L, 10L, 2L, 72L],
       [28237L, 10L, 3L, 71L],
       [28237L, 10L, 4L, 69L],
       [28237L, 160L, 1L, 67L],
       [28237L, 160L, 2L, 69L],
       [28237L, 160L, 3L, 68L],
       [28237L, 160L, 4L, 75L],
       [28237L, 170L, 1L, 72L],
       [28237L, 170L, 2L, 75L],
       [28237L, 180L, 1L, 71L],
       [28237L, 180L, 2L, 65L],
       [28237L, 180L, 3L, 68L],
       [28237L, 180L, 4L, 75L],
       [28237L, 200L, 1L, 78L],
       [28237L, 200L, 2L, 67L],
       [28237L, 200L, 3L, 78L],
       [28237L, 200L, 4L, 65L],
       [28237L, 220L, 1L, 74L],
       [28237L, 220L, 2L, 57L],
       [28237L, 220L, 3L, 68L],
       [28237L, 280L, 1L, 73L],
       [28237L, 280L, 2L, 70L],
       [28237L, 280L, 3L, 74L],
       [28237L, 280L, 4L, 66L],
       [28237L, 290L, 1L, 73L],
       [28237L, 290L, 2L, 64L],
       [28237L, 290L, 3L, 75L],
       [28237L, 290L, 4L, 71L],
       [28237L, 320L, 1L, 71L],
       [28237L, 320L, 2L, 67L],
       [2823

In [97]:
np.asarray((0,1))

array([0, 1])

[(28237L, datetime.datetime(2014, 2, 27, 0, 0), 734L, 1L, 63L),
 (28237L, datetime.datetime(2014, 2, 28, 0, 0), 734L, 2L, 66L),
 (28237L, datetime.datetime(2014, 3, 1, 0, 0), 734L, 3L, 70L),
 (28237L, datetime.datetime(2014, 3, 2, 0, 0), 734L, 4L, 76L),
 (28237L, datetime.datetime(2014, 3, 6, 0, 0), 8L, 1L, 57L),
 (28237L, datetime.datetime(2014, 3, 7, 0, 0), 8L, 1L, 14L),
 (28237L, datetime.datetime(2014, 3, 7, 0, 0), 8L, 2L, 76L),
 (28237L, datetime.datetime(2014, 3, 8, 0, 0), 8L, 3L, 76L),
 (28237L, datetime.datetime(2014, 3, 9, 0, 0), 8L, 4L, 75L),
 (28237L, datetime.datetime(2014, 4, 3, 0, 0), 729L, 1L, 71L),
 (28237L, datetime.datetime(2014, 4, 4, 0, 0), 729L, 2L, 72L),
 (28237L, datetime.datetime(2014, 4, 5, 0, 0), 729L, 3L, 76L),
 (28237L, datetime.datetime(2014, 4, 6, 0, 0), 729L, 4L, 65L),
 (28237L, datetime.datetime(2014, 5, 1, 0, 0), 698L, 1L, 69L),
 (28237L, datetime.datetime(2014, 5, 2, 0, 0), 698L, 2L, 78L),
 (28237L, datetime.datetime(2014, 5, 3, 0, 0), 698L, 3L, 65L),


In [36]:
conn.close()